export default function usernameGenerator(name: string): string {
  // Expanded list of adjectives
  const adjectives = [
    "super",
    "awesome",
    "brilliant",
    "cool",
    "fast",
    "strong",
    "fierce",
    "mighty",
    "wild",
    "electric",
    "dynamic",
    "smooth",
    "bold",
    "fearless",
    "swift",
    "stellar",
    "radiant",
    "savage",
    "intense",
    "incredible",
    "fantastic",
    "inspiring",
    "epic",
    "legendary",
    "magnificent",
    "powerful",
    "unbreakable",
    "unstoppable",
    "formidable",
    "unstoppable",
    "vibrant",
    "unstoppable",
    "invincible",
    "ferocious",
    "dynamic",
    "energetic",
    "fearless",
    "heroic",
    "unstoppable",
    "fiery",
    "limitless",
    "majestic",
    "noble",
    "audacious",
    "sharp",
    "explosive",
    "fiery",
    "tactical",
    "resilient",
    "dazzling",
    "indomitable",
    "phenomenal",
    "unstoppable",
    "sophisticated",
    "innovative",
    "unbeatable",
    "bold",
    "daring",
    "quick",
    "defiant",
    "sophisticated",
    "unstoppable",
    "pioneering",
    "unstoppable",
    "brave",
    "courageous",
    "tenacious",
    "fearless",
    "brilliant",
    "sharp",
    "unstoppable",
    "unstoppable",
    "strong",
    "resilient",
    "extraordinary",
    "famous",
    "unmatched",
    "gutsy",
    "unstoppable",
    "powerful",
    "confident",
    "sharp",
    "epic",
    "unstoppable",
    "dominant",
    "elite",
    "futuristic",
    "savant",
    "unstoppable",
    "agile",
    "visionary",
    "strong",
    "unstoppable",
    "radiant",
    "adventurous",
    "legendary",
    "unstoppable",
    "pivotal",
    "daring",
    "incredible",
    "impressive",
    "majestic",
    "reliable",
    "optimistic",
    "sharp",
    "unstoppable",
    "stunning",
  ];

  // Split the name and take only the first part (in case there is a second name)
  const firstName = name.split(" ")[0];

  // Randomly select an adjective
  const randomAdjective =
    adjectives[Math.floor(Math.random() * adjectives.length)];

  // Return the generated username
  return `${randomAdjective}${firstName}`;
}
